Change do path to /secret/do-token

diff --git a/do-float-ip b/do-float-ip
--- a/do-float-ip
+++ b/do-float-ip
@@ -28,8 +28,8 @@ main() {
   [[ "$#" -lt 1 ]] && fatal "$0 floating-ip-or-name"
   local ip=$1
 
-  DO_TOKEN=$(cat /etc/do.token 2>/dev/null) \
-    || fatal "/etc/do.token missing or unreadable"
+  DO_TOKEN=$(cat /secret/do.token 2>/dev/null) \
+    || fatal "/secret/do.token missing or unreadable"
 
   if [[ ! "$ip" =~ "^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$" ]]; then
     ip="$(getent hosts "$ip" | sed 's/ .*$//')"
